--CRIAR RELATÓRIO QUE MOSTRE OS PRODUTOS QUE NAO PRECISAM DE REPOSICAO NO ESTOQUE, USANDO OPERADO DE CONJUNTO SQL
CREATE VIEW produtos_es AS 
SELECT nome_es AS NOME, cor_es AS COR, tamanho_es AS TAMANHO FROM estoque_tmp
MINUS
SELECT nome_rep AS NOME, cor_rep AS COR, tamanho_rep AS TAMANHO FROM reposicao_tmp

--VALIDAR CRIACAO DO RELATÓRIO
SELECT * FROM produtos_es
