--CRIAR INDEX DE BITMAP
CREATE BITMAP INDEX idx_cor
ON estoque_tmp (cor_es);

--VALIDAR CRIACAO DE INDEX DE BITMAP
SELECT INDEX_NAME, INDEX_TYPE FROM ALL_INDEXES 
WHERE INDEX_NAME = 'IDX_COR' 
